name = "hugo-nagi"
license = "MIT"
licenselink = "https://github.com/amaotone/hugo-nagi/blob/master/LICENSE.md"
description = "hugo-nagi is a minimal hugo theme."
tags = ["blog"]
features = ["blog", "themes"]
min_version = 0.14

[author]
    name = "Amane Suzuki"
    homepage = "http://amalog.net/"
